window.questionsAnswersList =
    [["What startup, acquired by Facebook for $1 billion in 2012, became the fourth most downloaded app in the 2010s and is known for the posting of pictures?", "Instagram"],
    ["What is the programming language developed by James Gosling at Sun Microsystems and named after the type of coffee from Indonesia?", "Java"],
    ["Pierre Omidyar founded which popular online auction company in 1995 out of San Jose, California?", "eBay"],
    ["In 1999 Shigetaka Kurita invented what keyboard additions for cell phones that would eventually replace emoticons and even get their own movie?", "Emojis"],
    ["What word is often abbreviated as Fn on a keyboard?", "Function"],
    ["What popular operating system, launched in 1991, also has its own mascot, Tux the penguin?", "Linux"],
    ["The first FDA-approved telemedicine robot that uses autonomous movement technology is the RP-VITA, from the Roomba-making firm that shares what name with a Will Smith movie.", "iRobot"],
    ["THINK was the company motto for more than 40 years, for the company often referred to as 'Big Blue'. What is this frequently-acronymed company?", "IBM"],
    ["What delicious computer term did web browser programmer Lou Montulli coin to refer to information that is sent from the browser to the web server?", "Cookie"]
    ["Now appearing prophetic, what device was announced in 2007 with the following slogan? 'This is only the beginning.'", "iPhone"],
    ["Developed by Unimation, the Programmable Universal Manipulation Arm is also known by the much shorter name of what fierce animal?", "PUMA"],
    ["What is the 6-letter term for a group of computers that is networked together and used by hackers to steal information?", "Botnet"],
    ["A dude named Chip Morningstar received the first JSON message, a format derived from what core language repped by the 'JS'?", "JavaScript"],
    ["In 2022, Credit Kudos, a credit evaluation tool for lenders based out of the UK, was purchased by what technology giant with a fruit-based name?", "Apple"],
    ["Andy Rubin is known as one of the three founders of what massively popular cell phone operating system?", "Android"],
    ["What “A” antivirus software is a freeware solution available across multiple platforms, with an amoeba like orange “A” as a logo? It is also a pirate word meaning “Stop.”", "Avast"],
    ["Doug Engelbart was the inventor of what computer accessory? The first one was made from wood.", "Mouse"],
    ["The four principle wireless encryption standards available at most access points are WPA, WPA2, WPA3, and which less-secure fourth option?", "WEP"],
    ["In a 1987 film starring Peter Weller and Nancy Allen, the city of Detroit signs a deal with the company Omni Consumer Products to re-build parts of the city into a utopia and introduce a law enforcement robot ED-209. What is this film?", "RoboCop"],
    ["What is the seven-letter branded software standard created by Apple that enables a car radio or touchscreen to be a display and a controller for an iOS device?", "CarPlay"],
    ["What American tech company had a microprocessor facility in Costa Rica that at one time was responsible for 20% of Costa Rican exports and 5% of the country's GDP?", "Intel"],
    ["What simulation video game franchise was originally developed by Will Wright and launched in 1989 for the Macintosh computer?", "SimCity"],
    ["Composed for solo guitar by Francisco Tárrega in 1902, 'Grand Valse' is used as the distinctive ringtone of what Nordic telecom?", "Nokia"],
    ["In 2005, Linus Torvalds created software for tracking changes on files in order to improve development of the Linux kernel. Since 2005, the open-source software has had Junio Hamano as the core maintainer. What is the three-letter name of this uber-popular software among developers?", "Git"],
    ["What Japanese-based conglomerate used 'That '70s Show' star Ashton Kutcher to promote its Coolpix digital camera in a 2009 commercial?", "Nikon"],
    ["Tony Stark tries on his magnanimous dude persona at the start of 'Captain America: Civil War' by funding all student projects at what New England school?", "MIT"],
    ["Unicode, the standard for character encoding used to represent multilingual text as binary, is the successor of what US encoding standard?", "ASCII"],
    ["What company providing hosting for software development and distributed version control familiar to computer programmers is known for its iconic Octocat (part cat, part octopus) logo?", "Github"],
    ["A November 1998 article titled 'New CYBERSCAPE: Digital Assistants Get Sophisticated' was the first article in the New York Times's archive to use what now-ubiquitous word which, despite its name, does not necessarily refer to the IQ of a pocket computer?", "Smartphone"],
    ["Your computer is switching to a different _____ when you receive an HTTP code 101. What word fills in the blank?", "Protocol"],
    ["Maker of devices such as Nintendo gaming consoles, iPhones, and Amazon Kindle, the Taiwanese manufacturer Hon Hai Technology Group is better known by what 'sly' name?", "Foxconn"],
    ["What multinational technology and internet company, owner of Fitbit, launched its own Finance website in 2006, tracking stocks and earnings along with financial news?", "Google"],
    ["What company's mid 1960's 'Drafting System' is often considered a tipping point in revealing the benefits of computer-aided design (CAD)?", "IBM"],
    ["Officially announced in February 2019, the 'Mate X' folding cell phone will be manufactured and sold by what electronics giant?", "Huawei"]
    ]